"use client";

import { useState } from "react";
import Image from "next/image";
import { motion, useReducedMotion } from "framer-motion";
import { Cpu, Gauge, ShieldCheck } from "@phosphor-icons/react";

import styles from "@/components/home/VectantHome.module.css";

export function GpuProofChapter() {
  const [position, setPosition] = useState(54);
  const reduceMotion = useReducedMotion();

  return (
    <section id="gpu-hmr" className={styles.chapter}>
      <div className={styles.sectionShell}>
        <motion.div
          initial={reduceMotion ? false : { opacity: 0, y: 34 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.18 }}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          className={styles.gpuPanel}
        >
          <div className={styles.gpuCopy}>
            <div className={styles.metaLabel}>Proof-gated GPU HMR</div>
            <h2>Compiled code can move without losing the moment.</h2>
            <p>
              Vectant promotes a live patch only when state, ABI, output, and ledger checks agree. The public visual proof is ROCm/HIP; CUDA routes are validated in hardware-backed pilots.
            </p>
            <div className={styles.gpuSignals}>
              {[
                [Cpu, "Native boundary", "ABI and state checks"],
                [Gauge, "Visible output", "Before, diff, after"],
                [ShieldCheck, "Promotion gate", "Evidence before reload"],
              ].map(([Icon, title, copy]) => (
                <div key={title}>
                  <Icon size={17} weight="duotone" />
                  <span><strong>{title}</strong>{copy}</span>
                </div>
              ))}
            </div>
          </div>

          <div className={styles.gpuCompare} style={{ "--compare-position": `${position}%` }}>
            <div className={styles.gpuToolbar}>
              <span>ROCm/HIP visual proof</span>
              <strong>{position < 50 ? "before" : "after"}</strong>
            </div>
            <div className={styles.gpuStage}>
              <Image
                src="/product-proof/gpu-hmr-before.png"
                alt="GPU render before the compiled hot reload"
                fill
                sizes="(min-width: 1024px) 48vw, 100vw"
                className="object-cover"
              />
              <div className={styles.gpuAfter}>
                <Image
                  src="/product-proof/gpu-hmr-after.png"
                  alt="GPU render after the compiled hot reload"
                  fill
                  sizes="(min-width: 1024px) 48vw, 100vw"
                  className="object-cover"
                />
              </div>
              <div className={styles.gpuDivider} aria-hidden="true"><span /></div>
              <input
                type="range"
                min="0"
                max="100"
                value={position}
                onChange={(event) => setPosition(Number(event.target.value))}
                aria-label="Compare GPU output before and after hot reload"
                className={styles.gpuRange}
              />
            </div>
            <div className={styles.gpuDiff}>
              <Image src="/product-proof/gpu-hmr-diff.png" alt="Visual difference generated by the GPU hot reload" width={800} height={600} />
              <p>Output proof remains attached to the same live session.</p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

